package cz.cuni.mff.d3s.trupple.language.nodes.builtin.units.crt;

import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.frame.VirtualFrame;
import cz.cuni.mff.d3s.trupple.language.nodes.ExpressionNode;
import cz.cuni.mff.d3s.trupple.language.runtime.graphics.PascalGraphMode;
import cz.cuni.mff.d3s.trupple.parser.identifierstable.types.TypeDescriptor;
import cz.cuni.mff.d3s.trupple.parser.identifierstable.types.primitive.BooleanDescriptor;

/**
 * Node representing crt's keypressed subroutine. Current implementation supports this subroutine only in graphics mode
 * {@link cz.cuni.mff.d3s.trupple.language.nodes.builtin.units.graph }.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link KeyPressedNodeGen}
 */
public abstract class KeyPressedNode extends ExpressionNode {

    @Specialization
    boolean keyPressed(VirtualFrame frame) {
        return PascalGraphMode.keyPressed();
    }

    @Override
    public TypeDescriptor getType() {
        return BooleanDescriptor.getInstance();
    }

}
