package cz.cuni.mff.d3s.trupple.language.nodes.literals;

import com.oracle.truffle.api.dsl.Specialization;

import cz.cuni.mff.d3s.trupple.language.nodes.ExpressionNode;
import cz.cuni.mff.d3s.trupple.parser.identifierstable.types.TypeDescriptor;
import cz.cuni.mff.d3s.trupple.parser.identifierstable.types.primitive.CharDescriptor;

/**
 * Node representing char literal.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link CharLiteralNodeGen}
 */
public abstract class CharLiteralNode extends ExpressionNode {

	private final char value;

	CharLiteralNode(char value) {
		this.value = value;
	}

	@Specialization
	public char execute() {
		return value;
	}

    @Override
    public TypeDescriptor getType() {
        return CharDescriptor.getInstance();
    }

}
