package cz.cuni.mff.d3s.trupple.language.nodes.literals;

import com.oracle.truffle.api.dsl.Specialization;

import cz.cuni.mff.d3s.trupple.language.nodes.ExpressionNode;
import cz.cuni.mff.d3s.trupple.parser.identifierstable.types.TypeDescriptor;
import cz.cuni.mff.d3s.trupple.parser.identifierstable.types.primitive.BooleanDescriptor;

/**
 * Node representing boolean literal.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link LogicLiteralNodeGen}
 */
public abstract class LogicLiteralNode extends ExpressionNode {

	private final boolean value;

	LogicLiteralNode(boolean value) {
		this.value = value;
	}

	@Specialization
	public boolean execute() {
		return value;
	}

    @Override
    public TypeDescriptor getType() {
        return BooleanDescriptor.getInstance();
    }

}
