package cz.cuni.mff.d3s.trupple.language.nodes.literals;

import com.oracle.truffle.api.dsl.Specialization;
import cz.cuni.mff.d3s.trupple.language.nodes.ExpressionNode;
import cz.cuni.mff.d3s.trupple.language.runtime.customvalues.PascalSubroutine;
import cz.cuni.mff.d3s.trupple.parser.identifierstable.types.TypeDescriptor;
import cz.cuni.mff.d3s.trupple.parser.identifierstable.types.subroutine.SubroutineDescriptor;

/**
 * Node representing subroutine literal. This is used for example for passing subroutines as a parameter to another subroutine.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link SubroutineLiteralNodeGen}
 */
public abstract class SubroutineLiteralNode extends ExpressionNode {

    private final PascalSubroutine function;
    private final SubroutineDescriptor descriptor;

    SubroutineLiteralNode(PascalSubroutine function, SubroutineDescriptor descriptor) {
        this.function = function;
        this.descriptor = descriptor;
    }

    @Specialization
    public PascalSubroutine execute() {
        return function;
    }

    @Override
    public TypeDescriptor getType() {
        return descriptor;
    }

}
