language: java
python:
  - "2.7"
jdk:
  - oraclejdk8
before_install:
  - sudo pip install astroid==1.1.0
  - sudo pip install pylint==1.1.0
  - pylint --version
install:
  - git clone https://github.com/graalvm/mx.git
  - wget http://ftp.halifax.rwth-aachen.de/eclipse//eclipse/downloads/drops4/R-4.5.1-201509040015/ecj-4.5.1.jar
  - mv ecj-4.5.1.jar mx/ecj.jar
  - export JDT=mx/ecj.jar
  - wget https://lafo.ssw.uni-linz.ac.at/slavefiles/gate/eclipse-jdk8-linux-x86_64.tar.gz
  - tar -xvzf eclipse-jdk8-linux-x86_64.tar.gz
  - export ECLIPSE_EXE=eclipse/eclipse
script:
  - $TEST_COMMAND
env:
  - TEST_COMMAND='mx/mx gate --strict-mode'
  - TEST_COMMAND='mx/mx checkoverlap'
  - TEST_COMMAND='mx/mx canonicalizeprojects'
  - TEST_COMMAND='mx/mx checkstyle'
  - TEST_COMMAND='sh .travis.sigtest.sh'
  - TEST_COMMAND='mx/mx testdownstream'
matrix:
  allow_failures:
    - env: TEST_COMMAND='mx/mx testdownstream'
