package cz.cuni.mff.d3s.trupple.language.nodes.builtin.file;

import com.oracle.truffle.api.dsl.NodeChild;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.nodes.NodeInfo;
import cz.cuni.mff.d3s.trupple.language.runtime.customvalues.FileValue;
import cz.cuni.mff.d3s.trupple.language.nodes.ExpressionNode;
import cz.cuni.mff.d3s.trupple.language.nodes.statement.StatementNode;

/**
 * Node representing Pascal's built in reset procedure which opens file for writing.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link RewriteBuiltinNodeGen}
 */
@NodeInfo(shortName = "rewrite")
@NodeChild(value = "file", type = ExpressionNode.class)
public abstract class RewriteBuiltinNode extends StatementNode {

    @Specialization
    void rewrite(FileValue file) {
        file.openToWrite();
    }

}
