package cz.cuni.mff.d3s.trupple.language.nodes.builtin.io;

import com.oracle.truffle.api.dsl.GenerateNodeFactory;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.nodes.NodeInfo;
import cz.cuni.mff.d3s.trupple.language.PascalLanguage;

import java.util.Scanner;

/**
 * Node representing Pascal's readln subroutine.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link ReadlnBuiltinNodeFactory.ReadlnBuiltinNodeGen}
 */
@NodeInfo(shortName = "readln")
@GenerateNodeFactory
public abstract class ReadlnBuiltinNode extends ReadBuiltinNode {

    @Specialization
    public void read(Object[] arguments) {
	    if (arguments.length == 0) {
	        this.consumeNewLine();
        } else {
            super.read(arguments);
            this.consumeNewLine();
        }
    }

    private void consumeNewLine() {
        PascalLanguage.INSTANCE.getInput().nextLine();
    }
}
