package cz.cuni.mff.d3s.trupple.language.nodes.builtin.units.graph;

import com.oracle.truffle.api.dsl.NodeChild;
import com.oracle.truffle.api.dsl.NodeChildren;
import com.oracle.truffle.api.dsl.Specialization;
import cz.cuni.mff.d3s.trupple.language.runtime.customvalues.PascalString;
import cz.cuni.mff.d3s.trupple.language.nodes.ExpressionNode;
import cz.cuni.mff.d3s.trupple.language.nodes.statement.StatementNode;
import cz.cuni.mff.d3s.trupple.language.runtime.graphics.PascalGraphMode;

/**
 * Node representing graph' initgraph subroutine. The arguments are ignored since they are not useful on current hardware.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link InitGraphNodeGen}
 */
@NodeChildren({
        @NodeChild(type = ExpressionNode.class),
        @NodeChild(type = ExpressionNode.class),
        @NodeChild(type = ExpressionNode.class)
})
public abstract class InitGraphNode extends StatementNode {

    @Specialization
    void initGraph(long graphDriver, long graphMode, PascalString pathToDriver) {
        PascalGraphMode.init();
    }

}
